#!/bin/bash

# Move into tools directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

cd ..
rm -rf build

# Build larkin client
cd larkin
../third_party/node/node_modules/node-gyp/bin/node-gyp.js configure build
mkdir -p ../build
mv build ../build/larkin